name: task
description: A new Flutter project.

publish_to: 'none'

version: 0.0.0-alpha.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  taskw:
    path: ../taskw
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
