name: taskc
description: Provides Dart libraries for developing a Taskwarrior client to your Taskserver
version: 0.0.0-alpha.0

publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

executables:
  taskd-setup: taskd_setup

dependencies:
  built_value:
  collection:
  intl:
  uuid:

dev_dependencies:
  build_runner:
  built_value_generator:
  taskj:
    path: ../taskj
  taskw:
    path: ../taskw
  test:
